version: '3'
volumes:
  node_modules:

services:
  node:
    image: library/node:9.11.1
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: bash -c "yarn && yarn start"
    ports:
      - 8080:8080